Repository gloddy-dev/Gloddy-Server, pull requests merged in 2023-09, with the labels that each got.

#97 [CHORE]: Multipart max size 환경변수 설정
  src/main/resources/application.yml
Labels: chore

#100 [FEAT]: 회원 탈퇴 API 구현
  src/main/java/com/gloddy/server/apply/domain/handler/ApplyQueryHandler.java
  src/main/java/com/gloddy/server/apply/domain/handler/impl/ApplyQueryHandlerImpl.java
  src/main/java/com/gloddy/server/apply/infra/repository/ApplyJpaRepository.java
  src/main/java/com/gloddy/server/article/domain/service/ArticleDtoMapper.java
  src/main/java/com/gloddy/server/auth/api/AuthApi.java
  src/main/java/com/gloddy/server/auth/application/AuthService.java
  src/main/java/com/gloddy/server/auth/domain/User.java
  src/main/java/com/gloddy/server/auth/domain/service/UserSignOutPolicy.java
  src/main/java/com/gloddy/server/auth/domain/service/UserSignUpPolicy.java
  src/main/java/com/gloddy/server/auth/domain/vo/kind/Status.java
  src/main/java/com/gloddy/server/auth/exception/WithdrawRequirementsNotMetException.java
  src/main/java/com/gloddy/server/auth/security/UserDetailsServiceImpl.java
  src/main/java/com/gloddy/server/comment/domain/service/CommentDtoMapper.java
  src/main/java/com/gloddy/server/core/error/handler/errorCode/ErrorCode.java
  src/main/java/com/gloddy/server/group_member/application/GroupMemberService.java
  src/main/java/com/gloddy/server/group_member/domain/handler/GroupMemberQueryHandler.java
  src/main/java/com/gloddy/server/group_member/domain/handler/impl/GroupMemberQueryHandlerImpl.java
  src/main/java/com/gloddy/server/group_member/infra/repository/custom/GroupMemberJpaRepositoryCustom.java
  src/main/java/com/gloddy/server/group_member/infra/repository/impl/GroupMemberJpaRepositoryImpl.java
  src/main/java/com/gloddy/server/mate/application/MateSaveService.java
  src/main/java/com/gloddy/server/user/api/UserGetApi.java
  src/main/java/com/gloddy/server/user/application/UserFindService.java
  src/main/java/com/gloddy/server/user/application/UserGetService.java
  src/main/java/com/gloddy/server/user/application/UserUpdateService.java
  src/main/java/com/gloddy/server/user/application/facade/UserGetFacade.java
  src/main/java/com/gloddy/server/user/domain/handler/UserQueryHandler.java
  src/main/java/com/gloddy/server/user/domain/handler/impl/UserQueryHandlerImpl.java
  src/main/java/com/gloddy/server/user/infra/repository/UserJpaRepository.java
  src/main/java/com/gloddy/server/user/infra/repository/impl/UserJpaRepositoryImpl.java
Labels: feature

#102 [FEAT, FIX]: QA 3차 반영
  src/main/java/com/gloddy/server/auth/domain/User.java
  src/main/java/com/gloddy/server/authEmail/api/AuthEmailApi.java
  src/main/java/com/gloddy/server/authEmail/application/AuthEmailService.java
  src/main/java/com/gloddy/server/authEmail/domain/dto/request/AuthEmailRequest.java
  src/main/java/com/gloddy/server/authEmail/domain/service/.gitkeep
  src/main/java/com/gloddy/server/authEmail/domain/service/LoginUserVerifyEmailCodeExecutor.java
  src/main/java/com/gloddy/server/authSms/infra/ncloud/NcloudSmsClient.java
  src/main/java/com/gloddy/server/group/domain/dto/GroupRequest.java
  src/main/java/com/gloddy/server/group/domain/service/GroupFactoryImpl.java
  src/main/java/com/gloddy/server/group/domain/vo/GroupPlace.java
  src/main/java/com/gloddy/server/mate/domain/handler/MateQueryHandler.java
  src/main/java/com/gloddy/server/mate/domain/handler/impl/MateQueryHandlerImpl.java
  src/main/java/com/gloddy/server/mate/infra/repository/MateJpaRepository.java
  src/main/java/com/gloddy/server/user/application/facade/UserGetFacade.java
  src/test/java/com/gloddy/server/common/group/GroupApiTest.java
  src/test/java/com/gloddy/server/common/myGroup/GroupServiceTest.java
  src/test/java/com/gloddy/server/common/reliability/ReliabilityApiTest.java
  src/test/java/com/gloddy/server/domain/service/bean/TestGroupFactory.java
  src/test/java/com/gloddy/server/service/auth/VerifyEmailCodeAfterSignUpTest.java
Labels: feature, fix

#105 [FIX]: Cors 설정 변경 - 프런트 개발 환경 url 추가
  src/main/java/com/gloddy/server/config/WebConfig.java
Labels: feature, fix

#106 [CHORE]: CD workflow 구축 (Amazon ECS)
  .aws/task-definition.json
  .github/workflows/BuildTest.yml
  .github/workflows/DeployOnPRD.yml
  .github/workflows/DeployOnSTG.yml
  Dockerfile_prd
Labels: chore

#109 [FIX]: group 전체 조회 쿼리 수정 (종료된 모임 제외)
  src/main/java/com/gloddy/server/group/domain/handler/impl/GroupQueryHandlerImpl.java
  src/main/java/com/gloddy/server/group/infra/repository/custom/GroupJpaRepositoryCustom.java
  src/main/java/com/gloddy/server/group/infra/repository/impl/GroupJpaRepositoryImpl.java
Labels: fix
