Repository gloddy-dev/Gloddy-Server, pull requests merged in 2023-08, with the labels that each got.

#63 [FEAT]: Security Filter 단 예외 핸들링 (JWT)
  src/main/java/com/gloddy/server/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/gloddy/server/auth/jwt/filter/JwtExceptionHandleFilter.java
  src/main/java/com/gloddy/server/auth/security/config/SecurityConfig.java
  src/main/java/com/gloddy/server/core/error/handler/errorCode/ErrorCode.java
  src/main/java/com/gloddy/server/core/error/handler/exception/UserBusinessException.java
  src/main/java/com/gloddy/server/core/response/ErrorResponse.java
  src/test/java/com/gloddy/server/acceptance/auth/TokenFailTest.java
  src/test/java/com/gloddy/server/common/auth/AuthApiTest.java
Labels: feature

#64 [IMPROVE]: https 요청 처리
  src/main/java/com/gloddy/server/auth/security/config/SecurityConfig.java
  src/main/java/com/gloddy/server/config/SwaggerConfig.java
  src/main/java/com/gloddy/server/core/api/HealthCheckController.java
  src/main/java/com/gloddy/server/core/error/handler/errorCode/ErrorCode.java
  src/main/java/com/gloddy/server/core/error/handler/exception/DatabaseConnectionException.java
Labels: fix, improve

#68 [FIX]: 토큰 유효시간 이슈 해결
  src/main/java/com/gloddy/server/auth/jwt/JwtTokenBuilder.java
Labels: bug, fix

#69 [Fix]: health check db connection 획득 로직 제거
  src/main/java/com/gloddy/server/core/api/HealthCheckController.java
Labels: bug, fix

#70 feat: article 단건 조회 api 구현
  src/main/java/com/gloddy/server/apply/domain/dto/ApplyRequest.java
  src/main/java/com/gloddy/server/article/api/ArticleController.java
  src/main/java/com/gloddy/server/article/application/ArticleService.java
  src/main/java/com/gloddy/server/article/domain/Article.java
  src/main/java/com/gloddy/server/article/domain/dto/ArticleResponse.java
  src/main/java/com/gloddy/server/article/domain/service/ArticleDtoMapper.java
  src/main/java/com/gloddy/server/article/infra/repository/impl/ArticleJpaRepositoryImpl.java
  src/main/java/com/gloddy/server/auth/domain/User.java
  src/main/java/com/gloddy/server/group/domain/Group.java
  src/test/java/com/gloddy/server/query/article/FindAllByGroupFetchUserAndGroupAndCommendsTest.java
Labels: feature

#72 [FEAT]: 그룹 멤버 전체 조회 API 구현
  src/main/java/com/gloddy/server/auth/domain/User.java
  src/main/java/com/gloddy/server/group_member/api/GroupMemberGetApi.java
  src/main/java/com/gloddy/server/group_member/api/dto/GroupMemberResponse.java
  src/main/java/com/gloddy/server/group_member/application/GroupMemberFindService.java
  src/main/java/com/gloddy/server/group_member/application/GroupMemberService.java
  src/main/java/com/gloddy/server/group_member/application/GroupMemberUpdateService.java
  src/main/java/com/gloddy/server/group_member/domain/GroupMember.java
  src/main/java/com/gloddy/server/group_member/domain/handler/impl/GroupMemberQueryHandlerImpl.java
  src/main/java/com/gloddy/server/group_member/domain/service/GroupMemberDtoMapper.java
  src/main/java/com/gloddy/server/group_member/infra/repository/custom/GroupMemberJpaRepositoryCustom.java
  src/main/java/com/gloddy/server/group_member/infra/repository/impl/GroupMemberJpaRepositoryImpl.java
  src/test/java/com/gloddy/server/acceptance/group/GetExpectedGroupTest.java
  src/test/java/com/gloddy/server/acceptance/group/GetParticipatedGroupTest.java
  src/test/java/com/gloddy/server/acceptance/groupMember/GetAllGroupMemberTest.java
  src/test/java/com/gloddy/server/acceptance/reliability/UpdateReliabilityByAbsenceGroupTest.java
  src/test/java/com/gloddy/server/acceptance/reliability/UpdateReliabilityByEstimateTest.java
  src/test/java/com/gloddy/server/acceptance/reliability/UpdateReliabilityByMatedTest.java
  src/test/java/com/gloddy/server/acceptance/reliability/UpdateReliabilityByPraisedTest.java
  src/test/java/com/gloddy/server/common/BaseApiTest.java
  src/test/java/com/gloddy/server/common/group/GroupApiTest.java
Labels: feature

#73 [Feat]: 공지 게시글 조회 api 구현
  src/main/java/com/gloddy/server/article/api/ArticleController.java
  src/main/java/com/gloddy/server/article/application/ArticleService.java
  src/main/java/com/gloddy/server/article/domain/dto/ArticleResponse.java
  src/main/java/com/gloddy/server/article/domain/handler/ArticleQueryHandler.java
  src/main/java/com/gloddy/server/article/domain/handler/impl/ArticleQueryHandlerImpl.java
  src/main/java/com/gloddy/server/article/domain/service/ArticleDtoMapper.java
  src/main/java/com/gloddy/server/article/infra/repository/ArticleJpaRepository.java
  src/main/java/com/gloddy/server/article/infra/repository/impl/ArticleJpaRepositoryImpl.java
  src/main/java/com/gloddy/server/comment/application/CommentService.java
  src/main/java/com/gloddy/server/comment/domain/Comment.java
  src/main/java/com/gloddy/server/comment/domain/dto/CommentResponse.java
  src/main/java/com/gloddy/server/comment/domain/service/CommentDtoMapper.java
Labels: feature

#75 [CHORE]: Swagger Schema 정의 및 Cors 추가
  src/main/java/com/gloddy/server/apply/domain/dto/ApplyRequest.java
  src/main/java/com/gloddy/server/apply/domain/dto/ApplyResponse.java
  src/main/java/com/gloddy/server/article/domain/dto/ArticleRequest.java
  src/main/java/com/gloddy/server/article/domain/dto/ArticleResponse.java
  src/main/java/com/gloddy/server/auth/domain/dto/AuthRequest.java
  src/main/java/com/gloddy/server/auth/domain/dto/AuthResponse.java
  src/main/java/com/gloddy/server/authEmail/domain/dto/response/AuthEmailResponse.java
  src/main/java/com/gloddy/server/authSms/domain/dto/SmsRequest.java
  src/main/java/com/gloddy/server/authSms/domain/dto/SmsResponse.java
  src/main/java/com/gloddy/server/comment/domain/dto/CommentRequest.java
  src/main/java/com/gloddy/server/comment/domain/dto/CommentResponse.java
  src/main/java/com/gloddy/server/config/WebConfig.java
  src/main/java/com/gloddy/server/core/api/HealthCheckController.java
  src/main/java/com/gloddy/server/group/domain/dto/GroupRequest.java
  src/main/java/com/gloddy/server/group/domain/dto/GroupResponse.java
  src/main/java/com/gloddy/server/user/domain/dto/UserUpdateRequest.java
Labels: chore

#76 [FEAT]: 학교 검색 구현 (회원가입 시)
  src/main/java/com/gloddy/server/auth/security/config/SecurityConfig.java
  src/main/java/com/gloddy/server/search/school/School.java
  src/main/java/com/gloddy/server/search/school/api/SchoolSearchApi.java
  src/main/java/com/gloddy/server/search/school/api/dto/SchoolSearchResponse.java
  src/main/java/com/gloddy/server/search/school/infra/respository/SchoolJpaRepository.java
  src/main/java/com/gloddy/server/search/school/infra/respository/custom/SchoolJpaRepositoryCustom.java
  src/main/java/com/gloddy/server/search/school/infra/respository/impl/SchoolJpaRepositoryImpl.java
  src/main/java/com/gloddy/server/search/school/manager/SchoolSearchManager.java
  src/main/java/com/gloddy/server/search/school/manager/impl/SchoolSearchMysqlJpaManager.java
Labels: feature

#80 [FIX]: group 생성 및 조회, article 조회 dto 수정
  src/main/java/com/gloddy/server/article/api/ArticleController.java
  src/main/java/com/gloddy/server/article/application/ArticleService.java
  src/main/java/com/gloddy/server/article/domain/Article.java
  src/main/java/com/gloddy/server/article/domain/dto/ArticleResponse.java
  src/main/java/com/gloddy/server/article/domain/service/ArticleDtoMapper.java
  src/main/java/com/gloddy/server/auth/domain/User.java
  src/main/java/com/gloddy/server/group/domain/dto/GroupRequest.java
  src/main/java/com/gloddy/server/group/domain/dto/GroupResponse.java
  src/main/java/com/gloddy/server/group/domain/service/GroupDtoMapper.java
  src/main/java/com/gloddy/server/group/domain/service/GroupFactory.java
  src/main/java/com/gloddy/server/group/domain/vo/GroupPlace.java
  src/test/java/com/gloddy/server/common/group/GroupApiTest.java
  src/test/java/com/gloddy/server/common/reliability/ReliabilityApiTest.java
Labels: fix

#77 [FEAT]: 모임 나가기 api 구현
  src/main/java/com/gloddy/server/apply/api/ApplyApi.java
  src/main/java/com/gloddy/server/apply/application/ApplyService.java
  src/main/java/com/gloddy/server/group/domain/Group.java
  src/main/java/com/gloddy/server/group/domain/dto/GroupResponse.java
  src/main/java/com/gloddy/server/group/domain/service/GroupDtoMapper.java
  src/main/java/com/gloddy/server/group/domain/vo/GroupMemberVOs.java
  src/main/java/com/gloddy/server/group_member/api/GroupMemberDeleteApi.java
  src/main/java/com/gloddy/server/group_member/application/GroupMemberDeleteService.java
  src/main/java/com/gloddy/server/group_member/domain/handler/GroupMemberCommandHandler.java
  src/main/java/com/gloddy/server/group_member/domain/handler/impl/GroupMemberCommandHandlerImpl.java
  src/main/java/com/gloddy/server/group_member/event/GroupMemberLeaveEvent.java
  src/main/java/com/gloddy/server/reliability/domain/vo/ScoreMinusType.java
  src/main/java/com/gloddy/server/reliability/domain/vo/ScoreType.java
  src/main/java/com/gloddy/server/reliability/event/consumer/ReliabilityEventConsumer.java
Labels: feature, refactor

#85 [FIX]: DTO 관련 이슈 처리
  src/main/java/com/gloddy/server/article/domain/service/ArticleDtoMapper.java
  src/main/java/com/gloddy/server/auth/domain/User.java
  src/main/java/com/gloddy/server/comment/domain/service/CommentDtoMapper.java
  src/main/java/com/gloddy/server/core/utils/DateTimePatternConstants.java
  src/main/java/com/gloddy/server/core/utils/DateTimeUtils.java
  src/main/java/com/gloddy/server/group/api/GroupApi.java
  src/main/java/com/gloddy/server/group/application/GroupService.java
  src/main/java/com/gloddy/server/group/domain/dto/GroupResponse.java
  src/main/java/com/gloddy/server/group/domain/handler/GroupQueryHandler.java
  src/main/java/com/gloddy/server/group/domain/handler/impl/GroupQueryHandlerImpl.java
  src/main/java/com/gloddy/server/group/domain/service/GroupDtoMapper.java
  src/main/java/com/gloddy/server/group/infra/repository/GroupJpaRepository.java
  src/main/java/com/gloddy/server/mate/application/MateGetService.java
  src/main/java/com/gloddy/server/mate/domain/dto/MateResponse.java
  src/main/java/com/gloddy/server/user/domain/dto/UserGetResponse.java
  src/test/java/com/gloddy/server/acceptance/group/GetExpectedGroupTest.java
Labels: fix

#88 fix: comment 전체 조회 response dto 수정
  src/main/java/com/gloddy/server/comment/domain/Comment.java
  src/main/java/com/gloddy/server/comment/domain/dto/CommentResponse.java
  src/main/java/com/gloddy/server/comment/domain/service/CommentDtoMapper.java
Labels: fix

#90 [FEAT]: 나의 모임 탭 조회 API 구현
  src/main/java/com/gloddy/server/apply/api/ApplyApi.java
  src/main/java/com/gloddy/server/apply/application/ApplyService.java
  src/main/java/com/gloddy/server/apply/domain/Apply.java
  src/main/java/com/gloddy/server/apply/domain/dto/ApplyResponse.java
  src/main/java/com/gloddy/server/apply/domain/handler/ApplyQueryHandler.java
  src/main/java/com/gloddy/server/apply/domain/handler/impl/ApplyQueryHandlerImpl.java
  src/main/java/com/gloddy/server/apply/domain/service/ApplyDtoMapper.java
  src/main/java/com/gloddy/server/apply/domain/service/RejectedApplyCheckExecutor.java
  src/main/java/com/gloddy/server/apply/infra/repository/custom/ApplyJpaRepositoryCustom.java
  src/main/java/com/gloddy/server/apply/infra/repository/impl/ApplyJpaRepositoryImpl.java
  src/main/java/com/gloddy/server/group/domain/Group.java
  src/main/java/com/gloddy/server/group/domain/dto/GroupRequest.java
  src/main/java/com/gloddy/server/group/domain/dto/GroupResponse.java
  src/main/java/com/gloddy/server/group/domain/handler/GroupQueryHandler.java
  src/main/java/com/gloddy/server/group/domain/handler/impl/GroupQueryHandlerImpl.java
  src/main/java/com/gloddy/server/group/domain/service/GroupDtoMapper.java
  src/main/java/com/gloddy/server/group/domain/service/GroupFactory.java
  src/main/java/com/gloddy/server/group/infra/repository/custom/GroupJpaRepositoryCustom.java
  src/main/java/com/gloddy/server/group/infra/repository/impl/GroupJpaRepositoryImpl.java
  src/main/java/com/gloddy/server/group_member/application/GroupMemberService.java
  src/main/java/com/gloddy/server/group_member/domain/GroupMember.java
  src/main/java/com/gloddy/server/group_member/domain/handler/GroupMemberQueryHandler.java
  src/main/java/com/gloddy/server/group_member/domain/handler/impl/GroupMemberQueryHandlerImpl.java
  src/main/java/com/gloddy/server/group_member/infra/repository/custom/GroupMemberJpaRepositoryCustom.java
  src/main/java/com/gloddy/server/group_member/infra/repository/impl/GroupMemberJpaRepositoryImpl.java
  src/main/java/com/gloddy/server/myGroup/read/MyGroupReadController.java
  src/main/java/com/gloddy/server/myGroup/read/MyGroupReadService.java
  src/main/java/com/gloddy/server/myGroup/read/domainService/HostingGroupExistNewApplyChecker.java
  src/main/java/com/gloddy/server/myGroup/read/domainService/HostingGroupGetExecutor.java
  src/main/java/com/gloddy/server/myGroup/read/domainService/NotEstimatedGroupGetExecutor.java
  src/main/java/com/gloddy/server/myGroup/read/domainService/ParticipatingGroupGetExecutor.java
  src/main/java/com/gloddy/server/myGroup/read/domainService/RejectedGroupGetExecutor.java
  src/main/java/com/gloddy/server/myGroup/read/domainService/WaitingGroupGetExecutor.java
  src/main/java/com/gloddy/server/myGroup/read/domainService/facade/HostingGroupGetFacade.java
  src/main/java/com/gloddy/server/myGroup/read/dto/MyGroupResponse.java
  src/main/java/com/gloddy/server/myGroup/read/util/MyGroupDtoMapper.java
  src/main/java/com/gloddy/server/scrap/application/ScrapService.java
  src/test/java/com/gloddy/server/acceptance/apply/UpdateApplyTest.java
  src/test/java/com/gloddy/server/acceptance/group/CreateGroupTest.java
  src/test/java/com/gloddy/server/acceptance/group/GetExpectedGroupTest.java
  src/test/java/com/gloddy/server/common/BaseServiceTest.java
  src/test/java/com/gloddy/server/common/group/GroupApiTest.java
  src/test/java/com/gloddy/server/common/myGroup/MyGroupServiceTest.java
  src/test/java/com/gloddy/server/service/myGroup/GetHostingGroupTest.java
  src/test/java/com/gloddy/server/service/myGroup/GetNotEstimatedGroupTest.java
  src/test/java/com/gloddy/server/service/myGroup/GetParticipatingGroupTest.java
  src/test/java/com/gloddy/server/service/myGroup/GetRejectedGroupTest.java
  src/test/java/com/gloddy/server/service/myGroup/GetWaitingGroupTest.java
Labels: feature

#91 [CHORE]: 나의 모임 조회 Response Swagger Schema 반영
  src/main/java/com/gloddy/server/myGroup/read/dto/MyGroupResponse.java
Labels: chore

#92 [FIX]: Group 단건 조회 응답에 Scrap 여부값 추가
  src/main/java/com/gloddy/server/group/domain/dto/GroupResponse.java
  src/main/java/com/gloddy/server/group/domain/service/GroupChecker.java
  src/main/java/com/gloddy/server/group/domain/service/GroupDtoMapper.java
  src/main/java/com/gloddy/server/scrap/infra/repository/ScrapJpaRepository.java
Labels: fix

#96 [FEAT]: user Id로 마이페이지 조회 API 구현
  src/main/java/com/gloddy/server/apply/domain/Apply.java
  src/main/java/com/gloddy/server/apply/domain/handler/ApplyQueryHandler.java
  src/main/java/com/gloddy/server/apply/domain/handler/impl/ApplyQueryHandlerImpl.java
  src/main/java/com/gloddy/server/apply/infra/repository/ApplyJpaRepository.java
  src/main/java/com/gloddy/server/auth/domain/User.java
  src/main/java/com/gloddy/server/group/application/GroupService.java
  src/main/java/com/gloddy/server/group/domain/dto/GroupResponse.java
  src/main/java/com/gloddy/server/group/domain/service/GroupDtoMapper.java
  src/main/java/com/gloddy/server/praise/domain/Praise.java
  src/main/java/com/gloddy/server/user/api/UserGetApi.java
  src/main/java/com/gloddy/server/user/application/UserGetService.java
  src/main/java/com/gloddy/server/user/domain/service/UserDtoMapper.java
Labels: feature, fix
