Repository gloddy-dev/Gloddy-Server, pull requests merged in 2023-07, with the labels that each got.

#52 [REFACTOR]: Spring Boot 3.1.1 Migration
  .github/workflows/BuildTest.yml
  .github/workflows/DeployOnSTG.yml
  .gitignore
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/com/gloddy/server/ServerApplication.java
  src/main/java/com/gloddy/server/apply/domain/Apply.java
  src/main/java/com/gloddy/server/apply/domain/dto/ApplyRequest.java
  src/main/java/com/gloddy/server/article/api/ArticleController.java
  src/main/java/com/gloddy/server/article/domain/Article.java
  src/main/java/com/gloddy/server/article/domain/dto/ArticleRequest.java
  src/main/java/com/gloddy/server/article/domain/vo/ArticleImage.java
  src/main/java/com/gloddy/server/auth/api/AuthApi.java
  src/main/java/com/gloddy/server/auth/domain/User.java
  src/main/java/com/gloddy/server/auth/jwt/JwtTokenBuilder.java
  src/main/java/com/gloddy/server/auth/jwt/JwtTokenExtractor.java
  src/main/java/com/gloddy/server/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/gloddy/server/auth/security/config/SecurityConfig.java
  src/main/java/com/gloddy/server/authEmail/api/AuthEmailApi.java
  src/main/java/com/gloddy/server/authEmail/application/AuthEmailService.java
  src/main/java/com/gloddy/server/authEmail/domain/dto/request/AuthEmailRequest.java
  src/main/java/com/gloddy/server/comment/api/CommentController.java
  src/main/java/com/gloddy/server/comment/domain/Comment.java
  src/main/java/com/gloddy/server/comment/domain/dto/CommentRequest.java
  src/main/java/com/gloddy/server/config/QuerydslConfig.java
  src/main/java/com/gloddy/server/config/SwaggerConfig.java
  src/main/java/com/gloddy/server/core/converter/EnumArrayConverter.java
  src/main/java/com/gloddy/server/core/entity/common/BaseTimeEntity.java
  src/main/java/com/gloddy/server/file/config/AmazonS3Config.java
  src/main/java/com/gloddy/server/group/domain/Group.java
  src/main/java/com/gloddy/server/group/domain/vo/GroupDateTime.java
  src/main/java/com/gloddy/server/group/domain/vo/GroupMemberVO.java
  src/main/java/com/gloddy/server/group/domain/vo/GroupMemberVOs.java
  src/main/java/com/gloddy/server/group/domain/vo/GroupPlace.java
  src/main/java/com/gloddy/server/group_member/api/GroupMemberApi.java
  src/main/java/com/gloddy/server/group_member/domain/GroupMember.java
  src/main/java/com/gloddy/server/mate/domain/Mate.java
  src/main/java/com/gloddy/server/praise/domain/Praise.java
  src/main/java/com/gloddy/server/reliability/domain/Reliability.java
  src/main/java/com/gloddy/server/scrap/domain/Scrap.java
  src/main/java/com/gloddy/server/user/api/UserApi.java
  src/main/java/com/gloddy/server/user/application/UserService.java
  src/test/java/com/gloddy/server/common/BaseApiTest.java
  src/test/java/com/gloddy/server/query/QueryTest.java
  src/test/java/com/gloddy/server/query/TestConfig.java
Labels: refactor

#54 [CHORE]: Cors Configuration
  src/main/java/com/gloddy/server/config/WebConfig.java
Labels: bug

#56 [FIX]: Cors 설정 변경
  src/main/java/com/gloddy/server/auth/security/config/SecurityConfig.java
Labels: bug, fix

#57 [FEAT]: 휴대폰 인증 api 구현
  build.gradle
  src/main/java/com/gloddy/server/authEmail/exception/InvalidVerificationCodeException.java
  src/main/java/com/gloddy/server/authSms/api/SmsApi.java
  src/main/java/com/gloddy/server/authSms/application/SmsService.java
  src/main/java/com/gloddy/server/authSms/domain/SmsClient.java
  src/main/java/com/gloddy/server/authSms/domain/dto/SmsRequest.java
  src/main/java/com/gloddy/server/authSms/domain/dto/SmsResponse.java
  src/main/java/com/gloddy/server/authSms/infra/ncloud/NcloudProperties.java
  src/main/java/com/gloddy/server/authSms/infra/ncloud/NcloudSignatureMaker.java
  src/main/java/com/gloddy/server/authSms/infra/ncloud/NcloudSmsClient.java
  src/main/java/com/gloddy/server/authSms/infra/ncloud/NcloudSmsFeignClient.java
  src/main/java/com/gloddy/server/authSms/infra/ncloud/SmsFeignError.java
  src/main/java/com/gloddy/server/authSms/infra/ncloud/dto/NcloudSmsRequest.java
  src/main/java/com/gloddy/server/authSms/infra/ncloud/dto/NcloudSmsResponse.java
  src/main/java/com/gloddy/server/authSms/utils/RandomVerificationCodeGenerator.java
  src/main/java/com/gloddy/server/authSms/utils/VerificationCodeGenerator.java
  src/main/java/com/gloddy/server/authSms/utils/VerificationCodeUtil.java
  src/main/java/com/gloddy/server/config/OpenFeignConfig.java
  src/main/java/com/gloddy/server/core/error/handler/errorCode/ErrorCode.java
  src/main/java/com/gloddy/server/core/error/handler/exception/SmsBusinessException.java
  src/main/java/com/gloddy/server/core/error/handler/exception/VerificationCodeBusinessException.java
  src/main/java/com/gloddy/server/core/utils/RedisUtil.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: feature

#55 [FIX]: Auth 플로우 변경(휴대폰 인증 추가) 및 RefreshToken 생성
  src/main/java/com/gloddy/server/article/domain/service/ArticleDtoMapper.java
  src/main/java/com/gloddy/server/auth/api/AuthApi.java
  src/main/java/com/gloddy/server/auth/application/AuthService.java
  src/main/java/com/gloddy/server/auth/domain/User.java
  src/main/java/com/gloddy/server/auth/domain/dto/AuthRequest.java
  src/main/java/com/gloddy/server/auth/domain/dto/AuthResponse.java
  src/main/java/com/gloddy/server/auth/domain/service/UserFactory.java
  src/main/java/com/gloddy/server/auth/domain/vo/Phone.java
  src/main/java/com/gloddy/server/auth/domain/vo/School.java
  src/main/java/com/gloddy/server/auth/domain/vo/kind/Personality.java
  src/main/java/com/gloddy/server/auth/exception/InValidPhoneNumberException.java
  src/main/java/com/gloddy/server/auth/jwt/JwtAuthentication.java
  src/main/java/com/gloddy/server/auth/jwt/JwtToken.java
  src/main/java/com/gloddy/server/auth/jwt/JwtTokenBuilder.java
  src/main/java/com/gloddy/server/auth/jwt/JwtTokenExtractor.java
  src/main/java/com/gloddy/server/auth/jwt/JwtTokenIssuer.java
  src/main/java/com/gloddy/server/auth/jwt/JwtTokenKeyUsable.java
  src/main/java/com/gloddy/server/auth/jwt/JwtTokenValidator.java
  src/main/java/com/gloddy/server/auth/jwt/JwtUserAdapter.java
  src/main/java/com/gloddy/server/auth/jwt/constant/Constant.java
  src/main/java/com/gloddy/server/auth/jwt/exception/JwtTokenInvalidException.java
  src/main/java/com/gloddy/server/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/gloddy/server/auth/jwt/payload/AccessPayload.java
  src/main/java/com/gloddy/server/auth/jwt/payload/Payload.java
  src/main/java/com/gloddy/server/auth/jwt/payload/RefreshPayload.java
  src/main/java/com/gloddy/server/auth/jwt/payload/factory/AccessPayloadFactory.java
  src/main/java/com/gloddy/server/auth/jwt/payload/factory/PayloadFactory.java
  src/main/java/com/gloddy/server/auth/jwt/payload/factory/RefreshPayloadFactory.java
  src/main/java/com/gloddy/server/auth/jwt/type/TokenType.java
  src/main/java/com/gloddy/server/auth/security/UserDetailsServiceImpl.java
  src/main/java/com/gloddy/server/comment/domain/service/CommentDtoMapper.java
  src/main/java/com/gloddy/server/core/dto/UserInfoDto.java
  src/main/java/com/gloddy/server/core/error/handler/errorCode/ErrorCode.java
  src/main/java/com/gloddy/server/group_member/domain/dto/EstimateResponse.java
  src/main/java/com/gloddy/server/mate/application/MateGetService.java
  src/main/java/com/gloddy/server/user/application/UserService.java
  src/main/java/com/gloddy/server/user/domain/handler/UserCommandHandler.java
  src/main/java/com/gloddy/server/user/domain/handler/impl/UserCommandHandlerImpl.java
  src/main/java/com/gloddy/server/user/infra/repository/UserJpaRepository.java
  src/main/java/com/gloddy/server/user/infra/repository/custom/UserJpaRepositoryCustom.java
  src/main/java/com/gloddy/server/user/infra/repository/impl/UserJpaRepositoryImpl.java
  src/main/resources/application.yml
  src/test/java/com/gloddy/server/common/BaseApiTest.java
  src/test/resources/application.yml
Labels: enhancement, fix

#58 [FIX]: AuthEmailApi Controller -> RestController
  src/main/java/com/gloddy/server/authEmail/api/AuthEmailApi.java
Labels: bug, fix

#59 [FIX]: Spring Data Redis yml 변경 및 파일 업로드 API Open
  src/main/java/com/gloddy/server/auth/security/config/SecurityConfig.java
  src/main/java/com/gloddy/server/file/api/FileApi.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: bug, fix

#61 [FIX]: 회원가입 시 이미 가입된 유저 차단
  src/main/java/com/gloddy/server/auth/domain/service/UserFactory.java
  src/main/java/com/gloddy/server/auth/domain/service/UserSignUpPolicy.java
  src/main/java/com/gloddy/server/auth/domain/vo/Phone.java
  src/main/java/com/gloddy/server/auth/exception/AlreadyUserSignUpException.java
  src/main/java/com/gloddy/server/core/error/handler/errorCode/ErrorCode.java
Labels: fix
