Repository gloddy-dev/Gloddy-Server, pull requests merged in 2023-02, with the labels that each got.

#37 fix: article 조회, article에 대한 댓글 조회 api 분리
  src/main/java/com/gloddy/server/article/api/ArticleController.java
  src/main/java/com/gloddy/server/article/dto/ArticleResponse.java
  src/main/java/com/gloddy/server/article/service/ArticleService.java
  src/main/java/com/gloddy/server/comment/api/CommentController.java
  src/main/java/com/gloddy/server/comment/dto/CommentResponse.java
  src/main/java/com/gloddy/server/comment/service/CommentService.java
Labels: fix

#38 [Feat, Fix]: 유저 생성 시 칭찬 생성
  src/main/java/com/gloddy/server/auth/entity/User.java
  src/main/java/com/gloddy/server/auth/service/AuthService.java
  src/main/java/com/gloddy/server/core/utils/event/UserCreateEvent.java
  src/main/java/com/gloddy/server/core/utils/event/UserEventHandler.java
  src/main/java/com/gloddy/server/estimate/entity/Praise.java
  src/main/java/com/gloddy/server/estimate/repository/PraiseJpaRepository.java
  src/main/java/com/gloddy/server/estimate/service/PraiseSaveService.java
Labels: feature, fix

#39 feat: 소모임 찜 기능 구현
  src/main/java/com/gloddy/server/apply/handler/ApplyQueryHandler.java
  src/main/java/com/gloddy/server/apply/handler/impl/ApplyQueryHandlerImpl.java
  src/main/java/com/gloddy/server/scrap/api/ScrapApi.java
  src/main/java/com/gloddy/server/scrap/dto/ScrapResponse.java
  src/main/java/com/gloddy/server/scrap/entity/Scrap.java
  src/main/java/com/gloddy/server/scrap/repository/ScrapJpaRepository.java
  src/main/java/com/gloddy/server/scrap/service/ScrapService.java
Labels: feature
